# Generated by Django 3.0.8 on 2020-09-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200908_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buy_sell',
            field=models.BooleanField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='member_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='owned',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_price',
            field=models.FloatField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_id',
            field=models.IntegerField(default=''),
        ),
    ]
