# Generated by Django 3.0.8 on 2020-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20200908_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='buy_sell',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='member_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='owned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase_price',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='stock_id',
            field=models.IntegerField(),
        ),
    ]
