# Generated by Django 3.0.8 on 2020-09-09 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_id',
        ),
    ]
