# Generated by Django 3.0.8 on 2020-09-30 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='buy_sell',
            new_name='buy',
        ),
    ]
