# Generated by Django 3.0.8 on 2020-11-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20200930_2029'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stock_name',
            field=models.TextField(default='no'),
        ),
    ]
