# Generated by Django 3.0.8 on 2020-09-08 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_auto_20200822_2204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('price', models.FloatField()),
                ('change', models.FloatField()),
                ('perc', models.FloatField()),
                ('opening', models.FloatField()),
                ('max', models.FloatField()),
                ('min', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Stocks',
        ),
    ]
