# Generated by Django 3.0.8 on 2020-09-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_auto_20200908_1902'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stock',
            new_name='Stocks',
        ),
    ]
