# Generated by Django 3.0.8 on 2020-11-18 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='member',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='member',
            name='date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='lol@lil.pl', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='nick',
            field=models.TextField(default='lol'),
        ),
    ]
