# Generated by Django 3.0.8 on 2020-11-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_auto_20201118_1855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='date',
        ),
        migrations.AlterField(
            model_name='member',
            name='email',
            field=models.EmailField(default='non@non.non', max_length=254),
        ),
        migrations.AlterField(
            model_name='member',
            name='nick',
            field=models.TextField(),
        ),
    ]
