# Generated by Django 3.0.8 on 2020-11-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_auto_20201118_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='nick',
            new_name='name',
        ),
    ]
