# Generated by Django 3.0.8 on 2020-11-30 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20201120_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='capital',
            field=models.FloatField(default=20000),
        ),
    ]
